apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: css-doppler-backend
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
            namespace: external-secrets
